# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-18 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('departure', models.TimeField(blank=True, null=True)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('third_ac', models.PositiveIntegerField(default=10)),
                ('second_ac', models.PositiveIntegerField(default=10)),
                ('sleeper', models.PositiveIntegerField(default=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Route')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Train'),
        ),
        migrations.AddField(
            model_name='routepath',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='booking.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_path',
            field=models.ManyToManyField(through='booking.RoutePath', to='booking.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='booking.Station'),
        ),
    ]
