# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-24 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20171124_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
