# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-24 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20171124_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='phone',
        ),
    ]
