# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_ticket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
